// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzmatfnltgtgjvbputtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6bWF0Zm5sdGd0Z2p2YnB1dHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MzAxOTIsImV4cCI6MjA2NjIwNjE5Mn0.JEaWCyoC4FRwE8VuD0u-CwXYfDBp8tY0znXl-0OQ230";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);